name: SAST Test Pipeline

on:
  push:
    branches: [ main, implement_SAST ]
  pull_request:
    branches: [ main ]

jobs:
  # SAST – SonarQube Scan
  sast:
    name: SAST (SonarQube)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=devsecops-labs_vuln-bank-devsecops
            -Dsonar.organization=devsecops-labs
            -Dsonar.sources=.
            -Dsonar.python.version=3.9
            -Dsonar.python.security.rule.repositories=python-security,python-security-hotspot

      - name: Store SonarQube Results
        run: |
          mkdir -p security-results/sonarqube
          curl -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}" \
               "${{ secrets.SONAR_HOST_URL }}/api/issues/search?projectKeys=devsecops-labs_vuln-bank-devsecops" \
               > security-results/sonarqube/issues.json
          
          if [ -s security-results/sonarqube/issues.json ]; then
            echo "SonarQube results saved successfully"
          else
            echo "No SonarQube issues found"
            echo '{"issues": []}' > security-results/sonarqube/issues.json
          fi

      - name: Upload SonarQube Results
        uses: actions/upload-artifact@v4
        with:
          name: sonar-results
          path: security-results/sonarqube/
          retention-days: 90
